#%RAML 1.0
title: github-action-test

/test:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "status": "test success"
              }